### ISSUE TITLE
Back & Forward button in general song selection not updating currently shown songs

### ISSUE THREAD

**Issue by darint916** [sqz269/music-player#17]
Clicking back/forward will update the link directory, along with the pagination highlight, but the actual displayed albums don't change.
![image](https://user-images.githubusercontent.com/54857161/214211227-3c5b4356-f210-4ebd-bd96-de632c1cd81d.png)
![image](https://user-images.githubusercontent.com/54857161/214211315-f13acb1b-ceb5-429c-9215-a51d15ad6d80.png)

**Comment by sqz269** [comment]
This is due to the Homepage not watching changes in routes.
https://router.vuejs.org/guide/essentials/dynamic-matching.html#reacting-to-params-changes
